
server:
  port: 10000

# spring:
#   datasource:
#       url: jdbc:mongo://localhost:27017/moviebox
#       username: rootuser
#       password: rootpass
#       driver-class-name: mongodb.jdbc.MongoDriver

  # data:
  #   mongodb:
  #     host: "localhost"
  #     port: 27017
  #     database: "moviebox"
  #     username: ""
  #     password: ""


